name: MCPlugin
main: de.craftomania.plugin.MCPlugin.MCPlugin
commands:
  basic:
    description: arena
    usage: /arena args
    permission: MCPlugin.arena
    permission-message: You don't have <permission>